// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'b': string;
  'boat': string;
  'castle': string;
  'city': string;
  'compass': string;
  'desert': string;
  'desert2': string;
  'g': string;
  'grass': string;
  'grass2': string;
  'image': string;
  'letter': string;
  'mountain': string;
  'p': string;
  'r': string;
  'sea': string;
  'square': string;
  'tree': string;
  'y': string;
}
export const cssExports: CssExports;
export default cssExports;
